### ISSUE TITLE
Unable to create step definition with | operator with latest version

### ISSUE THREAD

**Issue by fayizkc** [cucumber/cucumber-expressions#299]
### 👓 What did you see?

When I try to create step as below
```
Then Verify "user" exist in the list
Then Verify "user" not exist in the list
```

with single step definition, it is not identifying. I have create stepDef as below
 
```
@Then ("Verify {string} (|not) exist in the list")
public void verifyUserExist(String username, String exist){
   if(exist.isEmpty){
     //check exist
 }
}
```

showing error as "Step undefined
You can implement this step using the snippet(s) below:"

### ✅ What did you expect to see?

This was working with older cucumber version I hope when i check in this [Issue](https://stackoverflow.com/questions/56380059/how-to-handle-logical-or-operation-from-cucumber-step-in-java)

### 📦 Which tool/library version are you using?

Cucumber version: 7.15.0

**Comment by mpkorstanje** [comment]
Capturing an optional element of expression is not possible with a Cucumber expressions. It looks like you may have been mixing regular and Cucumber Expressions. This should not have been possible and was fixed with https://github.com/cucumber/common/pull/771.

To match your step with regular expressions you would either have to use a regular expression

 * `^Verify "([^"]*)" (|not )exist in the list$`
 
Note: the extra space after not.

Or with Cucumber Expressions, you would use two separate step definitions. 

 * `Verify {string} not exist in the list`
 * `Verify {string} exist in the list`
 
The latter is probably better. While it does result in more lines of code, it keeps each step one focused on its own distinct task. If not you can probably factor out a more generic helper method.  Or use the regular expressions.
